# Site settings

title = "pick"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue",
# "green".
themeVariant = "blue"

[[menu.shortcuts]]
name = "Releases"
url = "https://github.com/bndw/pick/releases"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github"
url = "https://github.com/bndw/pick"
weight = 11
